include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    flutter_style_todos: false

# To disable any linter warnings or errors in generated files
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/firebase_options.dart'
  errors:
    invalid_annotation_target: ignore
    sort_pub_dependencies: false
    depend_on_referenced_packages: ignore
    invalid_use_of_visible_for_testing_member: ignore
