name: gorin_test_project
description: Test project for Gorin Systems

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hydrated_bloc: ^9.1.2
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_crashlytics: ^3.3.7
  reactive_forms: ^16.1.0
  firebase_storage: ^11.3.1
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  fluttertoast: ^8.2.2
  app_settings: ^5.1.1
  photo_view: ^0.14.0
  bcrypt: ^1.1.3
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

