// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AW9C55WD57dX7Uf0g6qwGnkuarcdIf4',
    appId: '1:463104400333:web:c4f0ce8b08bbf683dfc284',
    messagingSenderId: '463104400333',
    projectId: 'gorin-flutter-test',
    authDomain: 'gorin-flutter-test.firebaseapp.com',
    storageBucket: 'gorin-flutter-test.appspot.com',
    measurementId: 'G-HSLNFM7YG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFtn1SMKErV4xGiEULCVeHBR349s2M_kY',
    appId: '1:463104400333:android:fbe4a5668f67ac1ddfc284',
    messagingSenderId: '463104400333',
    projectId: 'gorin-flutter-test',
    storageBucket: 'gorin-flutter-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_eMz-C4O95dBcRQvwqSXtc4rDM6gSEWE',
    appId: '1:463104400333:ios:24a3529d2ff7f028dfc284',
    messagingSenderId: '463104400333',
    projectId: 'gorin-flutter-test',
    storageBucket: 'gorin-flutter-test.appspot.com',
    iosBundleId: 'com.gorinsystems.testproject.gorinTestProject.stg',
  );
}
