# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do |lane|
    Dotenv.overload '../../.env'
    environment = lane_context[SharedValues::ENVIRONMENT]
    unless environment.nil?
        puts "Load .env file of #{environment}"
        Dotenv.overload '../../.env.' + environment
    end
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute_android_apk do
      gradle(task: "clean assembleRelease")
      sh "flutter build apk -v --flavor #{ENV['ENVIRONMENT']}"
      firebase_app_distribution(
          app: ENV['FIREBASE_APP_ID'],
          service_credentials_file: "../firebase_app_distribution_credentials.json",
          apk_path: "../build/app/outputs/flutter-apk/app-#{ENV['ENVIRONMENT']}-release.apk",
          release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
          groups_file: "FirebaseAppDistributionConfig/groups.txt"
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
